# Generated by Django 5.2.10 on 2026-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_shop', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
