# Generated by Django 5.2.10 on 2026-02-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_shop', '0010_remove_product_image_remove_product_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thrift_shop.colour'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thrift_shop.size'),
        ),
    ]
