# Generated by Django 5.2.10 on 2026-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_shop', '0012_orderitem_colour_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
