# Generated by Django 5.2.10 on 2026-02-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_shop', '0015_order_placed_at_order_returned_at_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='placed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='returned_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
    ]
