# Generated by Django 5.2.10 on 2026-02-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_shop', '0016_remove_order_placed_at_remove_order_returned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images/desktop/')),
                ('mobile_image', models.ImageField(upload_to='home_images/mobile/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='home_videos/desktop/')),
                ('mobile_video', models.FileField(upload_to='home_videos/mobile/')),
            ],
        ),
    ]
