# Generated by Django 5.2.10 on 2026-02-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_shop', '0019_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
