# Generated by Django 5.2.10 on 2026-02-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_shop', '0020_product_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
